name: Playwright Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    container:
      options: --ipc=host
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: yarn
    - name: Run Playwright tests
      run: yarn playwright test --shard=${{ matrix.shard }}/${{ strategy.job-total }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blob-report-${{ matrix.shard }}
        path: blob-report
        retention-days: 30

  merge-reports:
    name: Merge reports
    if: ${{ !cancelled() }}
    needs: [test]
    uses: ./.github/workflows/merge-reports.yml
    secrets: inherit

  publish-report:
    name: Publish HTML report
    if: ${{ !cancelled() }}
    needs: [merge-reports]
    uses: ./.github/workflows/publish-report.yml
    secrets: inherit
